name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.3, 7.4, 8.0]
        laravel: [^6.0, ^7.0, ^8.0, ^9.0]
        scout: [^7.0, ^8.0, ^9.0]
        exclude:
          - php: 7.3
            laravel: ^8.0
          - php: 7.3
            scout: ^8.0
          - php: 7.4
            laravel: ^9.0
          - php: 7.4
            scout: ^9.0
          - php: 8.0
            laravel: ^6.0
          - laravel: ^6.0
            scout: ^8.0
          - laravel: ^6.0
            scout: ^9.0
          - laravel: ^7.0
            scout: ^9.0
          - laravel: ^8.0
            scout: ^7.0
          - laravel: ^9.0
            scout: ^7.0
          - laravel: ^9.0
            scout: ^8.0

    name: Test PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - Scout ${{ matrix.scout }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
           composer require "illuminate/contracts=${{ matrix.laravel }}" --no-update
           composer require "illuminate/database=${{ matrix.laravel }}" --no-update
           composer require "illuminate/support=${{ matrix.laravel }}" --no-update
           composer require "laravel/scout=${{ matrix.scout }}" --no-update
           composer update --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: vendor/bin/phpunit --verbose